export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const LOAD_CONTACTS = 'LOAD_CONTACTS';
export const SEARCH_CONTACTS = 'SEARCH_CONTACTS';